### PR TITLE
CMake: build dump_syms

### PR DESCRIPTION
**Pull request by dschmidt**

### CODE REVIEW

**Comment by jon-turney** [comment]
Thanks.

It would be nice if this build was exercised by CI, so I don't accidentally break it, but unfortunately CI seems to have bitrotted ...

**Comment by dschmidt** [comment]
Yeah, looks like. If you fix CI, I can add the CMake build

**Comment by jon-turney** [comment]
> If you fix CI

I'll try to look at that soon.

**Comment by jon-turney** [comment]
CI should be green if you rebase this.

**Comment by dschmidt** [comment]
One ci job failed apparently: https://ci.appveyor.com/project/jon-turney/google-breakpad/builds/29096560/job/kukyxy9r4pmub5b6

**Comment by jon-turney** [comment]
:sigh:

This is a sporadic failure I haven't got to the bottom of yet.

**Comment by dschmidt** [comment]
Alright, everything's green. Hope I find time this week to add the CMake test.

**Pull request merged**
